[book]
language = "en"
description = "docs template for Raven"
authors = ["subrat Gupta"]
multilingual = false
src = "src"
title = " RAVEN(R1) "

[rust]
edition = "2018"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/daveshap/raven"
edit-url-template = "https://github.com/daveshap/raven/tree/main/docs"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"